### ISSUE TITLE
Can you document usage?

### ISSUE THREAD

**Issue by matthew-dean** [rollup/rollup-plugin-legacy#1]
It's unclear what kind of object / type can be exported based on the documentation. Does the export have to be a plain object? Can there only be one export? Is that export "default" or is it a named export?

For instance, I'm trying to do:
```js
// legacy.js
var test = true;

// main.js
import test from './vendor/legacy';
```
```json
{
  "vendor/legacy.js": "test"
}
```
Even though the JSON config is being passed to rollup-plugin-legacy, it doesn't seem to import it.

**Comment by Rich-Harris** [comment]
I tried to do this in the README — if the value is a string, a default export will be created, if it's an object then each of the keys of that object will correspond to a named export. Is there a better way it could be explained?

Not sure why it's not working for you, can you provide a repro? [Here's mine](https://github.com/Rich-Harris/rollup-plugin-legacy-example), it seems to work fine.

**Comment by teohhanhui** [comment]
I'd expect it to work with node-style ids / paths, i.e. with `rollup-plugin-node-resolve`, but it does not.

**Comment by teohhanhui** [comment]
For example:

```js
const bundle = await rollup({
  ...
  plugins: [
    legacy({
      // 'woff2-feature-test': 'supportsWoff2',
      [`${nodeModulesPath}/woff2-feature-test/woff2.js`]: 'supportsWoff2',
    }),
    resolve({
      ...
    }),
  ],
  ...
}
```

**Comment by shellscape** [comment]
We'll have some better docs up for this plugin at `rollup/plugins`.
