### ISSUE TITLE
Add option to wrap inside an iife

### ISSUE THREAD

**Issue by wardpeet** [rollup/rollup-plugin-legacy#2]
I was wondering if it was possible to add an option to wrap a whole file and export it as a default  (I can create the PR if needed). 

For example:
third_party.js
```
console.log("I am a stupid module that has no export");
```
will transform into
```
export default () => { console.log("I am a stupid module that has no export"); }
```

Maybe it's not the use case of this plugin, if so I can create my own.

**Comment by Rich-Harris** [comment]
You're right, this functionality would belong in a different plugin 😀 Will close this issue, thanks
